const AUDIO_FX_PRESETS = [
  { key: 'reset',      icon: '\u21BA', text: 'Reset',            values: null },
  { key: 'crystal',    icon: '✨',    text: 'Clarté Studio',     values: { bass:   4, mid:  -2, treble:   6, lowPass: 20000, highPass:   30, reverb:  12, delay:   0 } },
  //{ key: 'bass',       icon: '↘️',    text: 'Bass',              values: { bass:  15, mid: -10, treble: -15, lowPass:  9000 } },
  //{ key: 'mid',        icon: '➡️',    text: 'Mid',               values: { bass: -15, mid:  10, treble: -12, lowPass: 20000, highPass:    0 } },
  //{ key: 'high',       icon: '↗️',    text: 'High',              values: { bass: -15, mid: -10, treble:  15, lowPass: 20000, highPass:  350 } },
  { key: 'earphones',  icon: '🎧',    text: 'Ecouteurs',         values: { bass: -15, mid: -12, treble:  10,                 highPass: 4000 } },
  { key: 'radio',      icon: '📻',    text: 'Radio',             values: { bass: -15, mid:  12, treble:  -9,                 highPass: 2000 } },
  { key: 'cave',       icon: '🕳️',    text: 'Cave',              values: { bass:  10,           treble:  -6, lowPass:  4000, highPass:    0, reverb:  80, delay:  30 } },
  { key: 'drown',      icon: '🌊',    text: 'Sous l\'eau',       values: { bass:  12,           treble: -10, lowPass:   600, highPass:  200, reverb:  80, delay:  20, speed: 95 } },
  { key: 'club',       icon: '🧱',    text: 'Voisin',            values: { bass:  12, mid: -12, treble: -15, lowPass:   900,                 reverb:  40 } },
  { key: 'church',     icon: '⛪',    text: 'Église',            values: {                                   lowPass: 10000, highPass:  100, reverb: 100, delay:  40 } },
  //{ key: 'liminal',    icon: '🌌',    text: 'Espace Liminal',    values: {            mid:   9,              lowPass:  4200, highPass: 2000, reverb:  90,             speed: 80 } },
  //{ key: 'void',       icon: '🌑',    text: 'Le Néant',          values: { bass: -15, mid: -15,                                              reverb: 100, delay:  40, speed: 70 } },
];